# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b134bc354c165bd8ef6868edb5fd7e5f60409f886b6cae78e75cf10a19bbf51635b9ff91b1815f898154fb61e58080136af2b53c8c77a384fdcd557f85ee7d6

test:
  secret_key_base: 5a7aa8f3ed2b2d79bcb92f6ebe2a325c53d7cdc9879b378990529b3fff3dac6251b6c111a25bd0bbd1a53e3b4bd8f7bc2dbb19085e953a2a5d466ffc6dea8dad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
